# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ace/chitt_workspace/eclipse_workspace/ChittMatrix

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ace/chitt_workspace/eclipse_workspace/ChittMatrix

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ace/chitt_workspace/eclipse_workspace/ChittMatrix/CMakeFiles /home/ace/chitt_workspace/eclipse_workspace/ChittMatrix/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ace/chitt_workspace/eclipse_workspace/ChittMatrix/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chittmatrix

# Build rule for target.
chittmatrix: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chittmatrix
.PHONY : chittmatrix

# fast build rule for target.
chittmatrix/fast:
	$(MAKE) -f CMakeFiles/chittmatrix.dir/build.make CMakeFiles/chittmatrix.dir/build
.PHONY : chittmatrix/fast

#=============================================================================
# Target rules for targets named chittvector

# Build rule for target.
chittvector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chittvector
.PHONY : chittvector

# fast build rule for target.
chittvector/fast:
	$(MAKE) -f CMakeFiles/chittvector.dir/build.make CMakeFiles/chittvector.dir/build
.PHONY : chittvector/fast

#=============================================================================
# Target rules for targets named test_chitt_matrix

# Build rule for target.
test_chitt_matrix: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_chitt_matrix
.PHONY : test_chitt_matrix

# fast build rule for target.
test_chitt_matrix/fast:
	$(MAKE) -f CMakeFiles/test_chitt_matrix.dir/build.make CMakeFiles/test_chitt_matrix.dir/build
.PHONY : test_chitt_matrix/fast

src/Matrix.o: src/Matrix.cpp.o
.PHONY : src/Matrix.o

# target to build an object file
src/Matrix.cpp.o:
	$(MAKE) -f CMakeFiles/chittmatrix.dir/build.make CMakeFiles/chittmatrix.dir/src/Matrix.cpp.o
.PHONY : src/Matrix.cpp.o

src/Matrix.i: src/Matrix.cpp.i
.PHONY : src/Matrix.i

# target to preprocess a source file
src/Matrix.cpp.i:
	$(MAKE) -f CMakeFiles/chittmatrix.dir/build.make CMakeFiles/chittmatrix.dir/src/Matrix.cpp.i
.PHONY : src/Matrix.cpp.i

src/Matrix.s: src/Matrix.cpp.s
.PHONY : src/Matrix.s

# target to generate assembly for a file
src/Matrix.cpp.s:
	$(MAKE) -f CMakeFiles/chittmatrix.dir/build.make CMakeFiles/chittmatrix.dir/src/Matrix.cpp.s
.PHONY : src/Matrix.cpp.s

src/test_ChittMatrix.o: src/test_ChittMatrix.cpp.o
.PHONY : src/test_ChittMatrix.o

# target to build an object file
src/test_ChittMatrix.cpp.o:
	$(MAKE) -f CMakeFiles/test_chitt_matrix.dir/build.make CMakeFiles/test_chitt_matrix.dir/src/test_ChittMatrix.cpp.o
.PHONY : src/test_ChittMatrix.cpp.o

src/test_ChittMatrix.i: src/test_ChittMatrix.cpp.i
.PHONY : src/test_ChittMatrix.i

# target to preprocess a source file
src/test_ChittMatrix.cpp.i:
	$(MAKE) -f CMakeFiles/test_chitt_matrix.dir/build.make CMakeFiles/test_chitt_matrix.dir/src/test_ChittMatrix.cpp.i
.PHONY : src/test_ChittMatrix.cpp.i

src/test_ChittMatrix.s: src/test_ChittMatrix.cpp.s
.PHONY : src/test_ChittMatrix.s

# target to generate assembly for a file
src/test_ChittMatrix.cpp.s:
	$(MAKE) -f CMakeFiles/test_chitt_matrix.dir/build.make CMakeFiles/test_chitt_matrix.dir/src/test_ChittMatrix.cpp.s
.PHONY : src/test_ChittMatrix.cpp.s

src/vector.o: src/vector.cpp.o
.PHONY : src/vector.o

# target to build an object file
src/vector.cpp.o:
	$(MAKE) -f CMakeFiles/chittvector.dir/build.make CMakeFiles/chittvector.dir/src/vector.cpp.o
.PHONY : src/vector.cpp.o

src/vector.i: src/vector.cpp.i
.PHONY : src/vector.i

# target to preprocess a source file
src/vector.cpp.i:
	$(MAKE) -f CMakeFiles/chittvector.dir/build.make CMakeFiles/chittvector.dir/src/vector.cpp.i
.PHONY : src/vector.cpp.i

src/vector.s: src/vector.cpp.s
.PHONY : src/vector.s

# target to generate assembly for a file
src/vector.cpp.s:
	$(MAKE) -f CMakeFiles/chittvector.dir/build.make CMakeFiles/chittvector.dir/src/vector.cpp.s
.PHONY : src/vector.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... chittmatrix"
	@echo "... chittvector"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test_chitt_matrix"
	@echo "... src/Matrix.o"
	@echo "... src/Matrix.i"
	@echo "... src/Matrix.s"
	@echo "... src/test_ChittMatrix.o"
	@echo "... src/test_ChittMatrix.i"
	@echo "... src/test_ChittMatrix.s"
	@echo "... src/vector.o"
	@echo "... src/vector.i"
	@echo "... src/vector.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

